TanimotoYuuki/EhimeGuri

- GameTemplate/Game/Assets/shader/model.fx
- GameTemplate/k2EngineLow/ModelRender.cpp
- GameTemplate/k2EngineLow/SceneLight.cpp
- GameTemplate/k2EngineLow/SceneLight.h
- GameTemplate/k2EngineLow/k2EngineLow.cpp
- GameTemplate/k2EngineLow/k2EngineLow.h
- GameTemplate/k2EngineLow/k2EngineLow.vcxproj
- GameTemplate/k2EngineLow/k2EngineLow.vcxproj.filters
- GameTemplate/k2EngineLow/k2EngineLowPreCompile.h
ディレクションライトの拡散反射光・鏡面反射光・環境光を実装しました。
> ディレクションライトの実装

- GameTemplate/k2EngineLow/CollisionObject.cpp
- GameTemplate/k2EngineLow/CollisionObject.h
- GameTemplate/k2EngineLow/Level3DRender.cpp
- GameTemplate/k2EngineLow/Level3DRender.h
- GameTemplate/k2EngineLow/k2EngineLow.cpp
- GameTemplate/k2EngineLow/k2EngineLow.h
- GameTemplate/k2EngineLow/k2EngineLow.vcxproj
- GameTemplate/k2EngineLow/k2EngineLow.vcxproj.filters
- GameTemplate/k2EngineLow/k2EngineLowPreCompile.h
> CollisionObject・Level3DRenderの実装

- GameTemplate/Game/Assets/shader/postEffect.fx
- GameTemplate/k2EngineLow/FontRender.cpp
- GameTemplate/k2EngineLow/FontRender.h
- GameTemplate/k2EngineLow/IRenderer.cpp
- GameTemplate/k2EngineLow/IRenderer.h
- GameTemplate/k2EngineLow/ModelRender.cpp
- GameTemplate/k2EngineLow/ModelRender.h
- GameTemplate/k2EngineLow/RenderingEngine.cpp
- GameTemplate/k2EngineLow/RenderingEngine.h
- GameTemplate/k2EngineLow/SpriteRender.cpp
- GameTemplate/k2EngineLow/SpriteRender.h
- GameTemplate/k2EngineLow/k2EngineLow.vcxproj
- GameTemplate/k2EngineLow/k2EngineLow.vcxproj.filters
- GameTemplate/k2EngineLow/k2EngineLowPreCompile.h
ポストエフェクトのモノクロ化を実装しました。
実装するためにRenderingEngineを改造しました。
> ポストエフェクトのモノクロ化実装

- GameTemplate/Game/Game.cpp
- GameTemplate/Game/Game.h
- GameTemplate/Game/GameOver.cpp
- GameTemplate/Game/GameOver.h
- GameTemplate/Game/Needle.cpp
- GameTemplate/Game/Needle.h
- GameTemplate/Game/Player.cpp
- GameTemplate/Game/Player.h
> GameOverの実装

- GameTemplate/Game/Game.cpp
- GameTemplate/Game/Player.cpp
> 奥行きの移動をなくした

- GameTemplate/Game/Game.cpp
- GameTemplate/Game/Game.h
- GameTemplate/Game/Player.cpp
> スタミナが減っている時だけ表示させるようにした

- GameTemplate/Game/Game.cpp
- GameTemplate/Game/Game.h
- GameTemplate/Game/Game.vcxproj
- GameTemplate/Game/Game.vcxproj.filters
- GameTemplate/Game/ScaffoldBlock.cpp
- GameTemplate/Game/ScaffoldBlock.h
・ScaffoldBlockクラスの追加
・制限時間を10秒から180秒に変更
> ScaffoldBlockクラスの追加

- GameTemplate/Game/Fade.cpp
- GameTemplate/Game/Fade.h
- GameTemplate/Game/Game.vcxproj
- GameTemplate/Game/Game.vcxproj.filters
- GameTemplate/Game/Title.cpp
- GameTemplate/Game/Title.h
- GameTemplate/Game/main.cpp
- GameTemplate/k2EngineLow/SpriteRender.h
ゲームをロードする時にフェードアウトしてその後にローディング画面を表示できるようにしました。
> ローディング画面実装

- GameTemplate/Game/Title.cpp
- GameTemplate/Game/Title.h
タイトル画面で遊び方用の画面を表示した時にステージモデルの動きを止めるようにしました。
> ステージモデルの動作の修正

- GameTemplate/Game/Game.vcxproj
- GameTemplate/Game/Game.vcxproj.filters
- GameTemplate/Game/StageClear.cpp
- GameTemplate/Game/StageClear.h
ステージクリア時の演出を実装しましたがインゲームにまだ入れていないの後で入れてください
> ステージクリア演出の実装

- GameTemplate/Game/BackGround.cpp
- GameTemplate/Game/Game.cpp
> 背景が2重で描画されていた不具合を修正

- GameTemplate/Game/Assets/shader/model.fx
- GameTemplate/Game/Enemy.cpp
- GameTemplate/k2EngineLow/SceneLight.cpp
・ディレクションライトの方向とカラーの変更をしました。
・敵モデルの影を描画できるようにしました。
・model.fxのソースコードの修正をしました。
> ソースコード修正・変更

- GameTemplate/Game/Enemy.cpp
> 敵が死んだときの当たり判定

- GameTemplate/Game/Game.cpp
- GameTemplate/Game/Towel.cpp
> アイテムの当たり判定を大きくした

- GameTemplate/Game/Game.cpp
- GameTemplate/Game/HS_FallingBlock.cpp
> 落ちる床をいったん消した

- GameTemplate/Game/GameClear.h
> ゲームクリア演出の修正

- GameTemplate/Game/GameClear.cpp
- GameTemplate/Game/GameOver.cpp
- GameTemplate/Game/GameOver.h
- GameTemplate/Game/Title.cpp
タイトルとゲームオーバーの選択の操作方法が分かりずらいので選択UIを表示しました。
> タイトルとゲームオーバーのUIの変更

- GameTemplate/Game/ClearPoint.cpp
- GameTemplate/Game/FallingBlock.cpp
- GameTemplate/Game/FallingBlock.h
- GameTemplate/Game/Game.cpp
- GameTemplate/Game/Game.h
- GameTemplate/Game/Needle.cpp
- GameTemplate/Game/Player.cpp
- GameTemplate/Game/S_MovingFloor.cpp
> ステージの全体的な修正

- GameTemplate/Game/FilePathConfig.h
- GameTemplate/Game/GameCamera.cpp
- GameTemplate/Game/Player.cpp
透明ブロックを何回か叩いたら当たり判定がなくなる不具合を修正しました。
> 透明ブロックの当たり判定がなくなる不具合の修正

- GameTemplate/Game/Block.cpp
- GameTemplate/Game/Block.h
- GameTemplate/Game/Fade.cpp
- GameTemplate/Game/Game.cpp
- GameTemplate/Game/Game.h
- GameTemplate/Game/GameClear.cpp
- GameTemplate/Game/GameOver.cpp
- GameTemplate/Game/Title.cpp
- GameTemplate/Game/TransparentBlock.cpp
- GameTemplate/Game/TransparentBlock.h
- GameTemplate/k2EngineLow/ModelRender.h
・ブロックを叩いたときにプレイヤーの頭がめり込んでいたのでブロックの当たり判定を修正しました。
・担当したコードのコメントを追加しました。
> ブロックの当たり判定の修正と担当したコードのコメントの追加

- GameTemplate/k2EngineLow/Level3DRender.cpp
- GameTemplate/k2EngineLow/Level3DRender.h
Level3DRenderクラスのDraw()が無かったので追加しました。
> Level3DRenderの修正

- GameTemplate/Game/Fade.cpp
- GameTemplate/Game/Fade.h
- GameTemplate/Game/Game.cpp
- GameTemplate/Game/GameClear.cpp
- GameTemplate/Game/GameOver.cpp
- GameTemplate/Game/StageClear.cpp
- GameTemplate/Game/Title.cpp
- GameTemplate/Game/Title.h
- GameTemplate/Game/TransparentBlock.cpp
・担当したコードのコメントを追加しました。
・担当したコードのマジックナンバーの解消をしました。
> 担当したコードのリファクタリング完了

- GameTemplate/Game/Assets/shader/backGround.fx
- GameTemplate/Game/Game.cpp
- GameTemplate/Game/Game.h
- GameTemplate/Game/GameClear.cpp
- GameTemplate/Game/GameOver.cpp
- GameTemplate/Game/StageClear.cpp
- GameTemplate/k2EngineLow/BackGroundRender.h
- GameTemplate/k2EngineLow/RenderingEngine.cpp
・特定の位置まで行ったらステージ背景を変更する演出を実装しました。
・ステージ背景をぼかし背景以外も見やすくしました。
> ステージ背景を変更する時の演出の実装とステージ背景の画像加工

- GameTemplate/Game/ClearPoint.cpp
- GameTemplate/Game/ClearPoint.h
- GameTemplate/Game/Game.cpp
- GameTemplate/Game/Game.h
- GameTemplate/Game/GameCamera.cpp
- GameTemplate/Game/GameCamera.h
- GameTemplate/Game/GameTimer.cpp
- GameTemplate/Game/GameTimer.h
- GameTemplate/Game/Player.cpp
- GameTemplate/Game/Player.h
- GameTemplate/Game/Stage2.cpp
- GameTemplate/Game/StageClear.cpp
- GameTemplate/Game/StageClear.h
- GameTemplate/Game/main.cpp
・ステージ2へ遷移する時の処理を追加しました。
->プレイヤーの位置・角度、カメラの位置・注視点、ステージ1のオブジェクトの削除、ステージ2用の制限時間の設定
・ステージ2用の中間地点を追加しました。
> ステージ2へ遷移する時の処理の追加とステージ2用の中間地点の追加

- GameTemplate/Game/ClearPoint.cpp
- GameTemplate/Game/ClearPoint.h
- GameTemplate/Game/Fade.cpp
- GameTemplate/Game/Fade.h
- GameTemplate/Game/Game.cpp
- GameTemplate/Game/Game.h
- GameTemplate/Game/GameClear.cpp
- GameTemplate/Game/GameClear.h
- GameTemplate/Game/GameOver.cpp
- GameTemplate/Game/GameOver.h
- GameTemplate/Game/Player.cpp
- GameTemplate/Game/Player.h
- GameTemplate/Game/Scene.cpp
- GameTemplate/Game/StageClear.cpp
- GameTemplate/Game/Title.cpp
- GameTemplate/Game/main.cpp
- GameTemplate/k2EngineLow/SpriteRender.h
- GameTemplate/k2EngineLow/gameObject/GameObjectManager.h
ステージ2をクリアした時にゲームがクラッシュする不具合を修正しました。
> ステージ2をクリアした時にゲームがクラッシュする不具合の修正

- GameTemplate/Game/Jako.cpp
- GameTemplate/Game/Mikan.cpp
- GameTemplate/Game/Taruto.cpp
- GameTemplate/Game/Towel.cpp
- GameTemplate/Game/sinju.cpp
・じゃこ天
・みかん
・真珠
・タルト
・タオル
このアイテムを取った時のエフェクトの表示位置を変更しました。
> アイテムを取った時のエフェクトの表示位置の変更
